import type { Metadata } from "next";
import { Inter, Geist, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import React, { Suspense } from "react";
import { ThemeProvider } from "@/components/ui/theme-provider";
import AppSidebar from "@/components/layout/Sidebar"; // added
import { SidebarProvider } from "@/components/ui/sidebar";

const fontImport = Geist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={fontImport.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-[100vh] flex">
            <SidebarProvider className="h-full">
              <Suspense fallback={<div className="w-64 border-r h-screen" />}>
                <AppSidebar />
              </Suspense>
              <main className="grow-1 h-full shrink-0">{children}</main>
            </SidebarProvider>{" "}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
