import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ThemeProvider } from "@/components/ui/theme-provider";
import AppSidebar from "@/components/layout/Sidebar"; // added

const urbanist = Inter({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={urbanist.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-[100vh] flex">
            <AppSidebar />
            <main className=" grow-1 h-full shrink-0">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
